[package]
name = "korlang-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
korlang-compiler = { path = "../../compiler" }

