[package]
name = "kpm"
version = "0.1.0"
edition = "2021"

[lib]
name = "kpm"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
serde_json = "1"
semver = "1"
